services:
  minecraft:
    image: docker.io/marctv/minecraft-papermc-server:latest
    restart: always
    container_name: "mcserver"
    environment:
      MEMORY: "1G"
      PAPERMC_FLAGS: ""
    volumes:
      - "/home/pi/mcserver:/data:rw"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true
